server {
	listen 80;
	server_name 127.0.0.1;
	allow 127.0.0.1;
	deny all;

    # 可以查看 nginx 状态
	location /nginx_status {
		stub_status on;
		access_log off;
	}

	# 可以查看 php8.4-fpm 状态
		# 需要确保 php8.4-fpm 的配置文件中有以下配置：
		# pm.status_path = /phpfpm_84_status
	location /phpfpm_84_status {
		include fastcgi.conf;
		fastcgi_pass unix:/run/php/php8.4-fpm.sock;
		fastcgi_param SCRIPT_FILENAME $fastcgi_script_name;
	}
}